[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.25"
evm_version = "cancun"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

[rpc_endpoints]
local = "http://127.0.0.1:8545"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
